dist: trusty
sudo: required
language: cpp
compiler: 
  - clang
matrix: 
  include:
    - os: linux
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-6.0"
    - os: osx
      osx_image: xcode8

script: 
  - make -j5
