dist: trusty
sudo: required
language: cpp
compiler: clang
matrix: 
  include:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - openjdk-8-jdk 
            - build-essential 
            - clang-6.0 
            - cmake
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-6.0"
    - os: osx
      osx_image: xcode8

script: 
  - make -j5
