dist: trusty
sudo: required
language: cpp
compiler: 
  - clang
  - gcc
matrix: 
  include:
    - os: linux
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-6.0"
    - os: osx
      osx_image: xcode8

script: 
  - make -j5
