dist: trusty
language: cpp
compiler: clang
matrix: 
  include:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    - os: osx
      osx_image: xcode8

script: 
  - ls -la
  - make -j5
